#!/usr/bin/env python3
"""Generate the library's INDEX.md navigation from card frontmatter.

Indexes are derived navigation, never a source of truth. Everything here comes
from the cards themselves — `name`, `object_type`, `stage_binding`, `variants`,
and `prerequisite_for` links — so an index cannot drift from what the library
actually contains. Regenerate rather than hand-edit.

    python PASS/tools/build_index.py                      # rewrite every index
    python PASS/tools/build_index.py --package metaskills # one package
    python PASS/tools/build_index.py --check              # fail if any is stale

A directory gets an index when it holds cards directly or has a descendant that
does. A directory's display name comes from `display_name` in its MODULE.yaml
when present, otherwise from the folder name.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from paths import default_library_root

HEADER = "<!-- GENERATED by tools/build_index.py; do not hand-edit. -->"
READING_NOTE = "_Read a foundation before the skills that build on it (`prerequisite_for`)._"
FM_RE = re.compile(r"\A---\r?\n(?P<front>.*?)\r?\n---\r?\n", re.S)
SKIP_NAMES = {"INDEX.md", "README.md"}


@dataclass(frozen=True)
class Card:
    path: Path
    data: dict[str, Any]

    @property
    def name(self) -> str:
        return str(self.data.get("name", self.path.stem))

    @property
    def object_id(self) -> str:
        return str(self.data.get("object_id", ""))


def load_cards(library: Path) -> list[Card]:
    cards: list[Card] = []
    for path in sorted(library.rglob("*.md")):
        if path.name in SKIP_NAMES:
            continue
        match = FM_RE.match(path.read_text(encoding="utf-8"))
        if not match:
            continue
        data = yaml.safe_load(match.group("front"))
        if isinstance(data, dict) and data.get("object_id"):
            cards.append(Card(path, data))
    return cards


def display_name(directory: Path) -> str:
    module = directory / "MODULE.yaml"
    if module.is_file():
        data = yaml.safe_load(module.read_text(encoding="utf-8"))
        if isinstance(data, dict) and data.get("display_name"):
            return str(data["display_name"])
    return directory.name.replace("-", " ").title()


def title_for(directory: Path, library: Path) -> str:
    parts: list[str] = []
    current = directory
    while current != library:
        parts.append(display_name(current))
        current = current.parent
    return " / ".join(reversed(parts))


def index_directories(library: Path, cards: list[Card]) -> set[Path]:
    """Every directory holding cards, plus each of its ancestors below library."""
    directories: set[Path] = set()
    for card in cards:
        current = card.path.parent
        while current != library:
            directories.add(current)
            current = current.parent
    return directories


def sort_key(card: Card) -> str:
    """Names sort case-insensitively, so 'Make a ...' precedes 'Make Member ...'."""
    return card.name.casefold()


def variant_summary(card: Card) -> str | None:
    entries = [
        f"`{variant['variant_name']}` ({variant['variant_basis']})"
        for variant in card.data.get("variants") or []
        if isinstance(variant, dict) and variant.get("variant_name") and variant.get("variant_basis")
    ]
    # Declared order, not sorted: a card lists its variants in the order that
    # makes sense to read them.
    return f"  - Variants: {'; '.join(entries)}." if entries else None


def reading_order_lines(subtree_cards: list[Card], names: dict[str, str]) -> list[str]:
    lines: list[str] = []
    for card in sorted(subtree_cards, key=sort_key):
        targets = sorted(
            names.get(str(link["target_object_id"]), str(link["target_object_id"]))
            for link in card.data.get("cross_links") or []
            if isinstance(link, dict) and link.get("rel") == "prerequisite_for" and link.get("target_object_id")
        )
        if not targets:
            continue
        lines.append(f"- **{card.name}** — read first")
        lines.extend(f"  - then: {target}" for target in targets)
    return lines


def render(directory: Path, library: Path, cards: list[Card], directories: set[Path]) -> str:
    names = {card.object_id: card.name for card in cards}
    own = sorted((c for c in cards if c.path.parent == directory), key=sort_key)
    subtree = [c for c in cards if directory in c.path.parents]
    children = sorted(d for d in directories if d.parent == directory)

    out = [HEADER, "", f"# {title_for(directory, library)}"]

    reading = reading_order_lines(subtree, names)
    if reading:
        out += ["", "## Reading order", "", READING_NOTE, ""] + reading

    if own:
        out += ["", "## Objects", ""]
        for card in own:
            out.append(
                f"- [{card.name}]({card.path.name}) - "
                f"{card.data.get('object_type')}; {card.data.get('stage_binding')}."
            )
            variants = variant_summary(card)
            if variants:
                out.append(variants)

    if children:
        out += ["", "## Topics", ""]
        for child in children:
            count = sum(1 for c in cards if child == c.path.parent or child in c.path.parents)
            out.append(f"- [{display_name(child)}]({child.name}/INDEX.md) - {count} object(s).")

    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--library", type=Path, default=default_library_root())
    parser.add_argument("--package", help="limit to one top-level package")
    parser.add_argument("--check", action="store_true", help="report stale indexes without writing")
    args = parser.parse_args()
    if not args.library.is_dir():
        print(f"FAIL: library root not found: {args.library.as_posix()}", file=sys.stderr)
        return 1

    library = args.library
    cards = load_cards(library)
    directories = index_directories(library, cards)
    if args.package:
        scope = library / args.package
        directories = {d for d in directories if d == scope or scope in d.parents}
        if not directories:
            print(f"No cards found in package '{args.package}'.")
            return 1

    stale: list[str] = []
    written = 0
    for directory in sorted(directories):
        target = directory / "INDEX.md"
        content = render(directory, library, cards, directories)
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            continue
        if args.check:
            stale.append(f"{'stale' if current is not None else 'missing'}: {target.relative_to(library).as_posix()}")
            continue
        target.write_text(content, encoding="utf-8", newline="")
        written += 1

    if args.check:
        for line in stale:
            print(line)
        if stale:
            print(f"FAIL: {len(stale)} index/indices out of date")
            return 1
        print(f"PASS: {len(directories)} index/indices are current")
        return 0
    print(f"Wrote {written} index/indices ({len(directories)} checked).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
